site_name: cqs
nav:
    - Home: index.md
    - 'Require': require.md
    - 'ui':
        - 'Box': ui/box.md
        - 'Label': ui/label.md
        - 'Widget': ui/widget.md
        - 'Window': ui/window.md

theme: readthedocs
markdown_extensions:
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
